name: 'StudioX 이슈 생성'
description: 'studioX FE Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [ order ]
title: '이슈 제목'
body:
  - type: input
    id: parentKey 
    attributes:
      label: 'Jira Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요.'
      placeholder: 'STUD-00'
    validations:
      required: true

  - type: input
    id: branchName
    attributes:
      label: '브랜치 이름 (이슈 요약)'
      description: '영문 소문자로 브랜치 이름을 지어주세요. (ex: login-error)'
    validations:
      required: true

  - type: dropdown
    id: branchPrefix
    attributes:
      label: '브랜치 전략(GitFlow)'
      options:
        - feature
        - fix
        - docs
        - style
        - refactor
        - test
        - chore
        - hotfix
        - release
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: '이슈 내용을 자세히 설명해주세요.'
      value: |
        - 상세 내용에 대해 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업 목록을 작성해주세요.'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true