export const priceData = [
  {
    name: "Basic",
    for: "for individual creaters",
    yearlyPrice: 15,
    monthlyPrice: 15,
    subtitle: "Basic plan only available in monthly",
    buttonText: "Try for Free",
    features: [
      "300 credits / month",
      "10GB cloud storage",
      "Image & video downloads",
      "StudioX watermark removal",
      "Unlimited AI chat editing (text only)",
      "Reference image attachment: 15 times / month",
    ],
  },
  {
    name: "Standard",
    for: "for professional creators",
    yearlyPrice: 3,
    monthlyPrice: 33,
    subtitle: {
      yearly: "$3 USD/mo",
      monthly: "$33 USD/mo",
    },
    buttonText: "Try for Free",
    features: [
      "900 credits / month",
      "50GB cloud storage",
      "Image & video downloads",
      "StudioX watermark removal",
      "Unlimited AI chat editing (with reference images)",
      "Image history & version management",
    ],
  },
  {
    name: "Pro",
    for: "for professional marketers & teams",
    yearlyPrice: 5,
    monthlyPrice: 59,
    subtitle: {
      yearly: "$5 USD/mo",
      monthly: "$59 USD/mo",
    },
    buttonText: "Try for Free",
    features: [
      "3,000 credits / month",
      "200GB cloud storage",
      "Image & video downloads",
      "StudioX watermark removal",
      "Unlimited AI chat editing (with reference images)",
      "Image history & version management",
      "Team collaboration (invite up to 5 members)",
      "Priority chat & email support",
    ],
  },
  {
    name: "Enterprise",
    for: "for organizations needing large-scale collaboration & custom support",
    yearlyPrice: null,
    monthlyPrice: null,
    subtitle: "Custom pricing",
    buttonText: "Book Demo",
    features: [
      "Flexible credits (including unlimited)",
      "1TB+ cloud storage",
      "Image & video downloads",
      "StudioX watermark removal",
      "Unlimited AI chat editing (with reference images)",
      "Image history & version management",
      "Team seats unlimited & real-time collaboration",
      "Brand-specific templates & brand kit",
      "Dedicated Customer Success Manager",
      "Custom onboarding & AI training",
      "Enterprise-grade security",
    ],
  },
];
