import type { Metadata } from "next";
import "./globals.css";
import { pretendard, calSans } from "./font";
import QueryProvider from "./query-provider";

export const metadata: Metadata = {
  title: "Studio X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${calSans.variable} scroll-smooth`}
    >
      <body className="h-full antialiased">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
