import type { Metadata } from "next";
import "./globals.css";
import { pretendard, calSans } from "./font";

export const metadata: Metadata = {
  title: "Studio X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} ${calSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
